feat: add custom color theme support
fvrests/lavender pull request #35
Opened 2024-11-21 21:23 UTC by jatindotdev

This pull request introduces a new custom color theme feature. The most important changes include the addition of a custom color theme, updates to the options menu to support the new theme, and utility functions to handle color processing.

https://github.com/user-attachments/assets/d70d2f4e-4d06-46af-891e-e6e02acf2222

### Custom Color Theme Feature:

* [`src/assets/styles/global.css`](diffhunk://#diff-8e57e24fafbd8da9941d9aee878f522b211c70ca8a5a07d21766dcea0d1421b1R44-R46): Added custom color variables and updated theme classes to include the custom theme.
* [`src/store/options.ts`](diffhunk://#diff-98ea41b4e17019f0d1d6af1076cab56e3ab691fd859d8a3e2b3699cf7ef60c9bR3-R11): Added `customColor` to the theme state and a method to set and preview the custom color.

### Options Menu Updates:

* [`src/components/options.vue`](diffhunk://#diff-3f290800f7cd843bda4d4bee83912235c149b9816a65cfa6e80e8a76207c5f3eR13): Integrated the custom color theme into the options menu, including input handling and theme selection.

### Utility Functions:

* [`src/utils/helpers.ts`](diffhunk://#diff-d9b0865f2e8f841410cd4faf3e1e4a1fb7cb0b545f583f6adaad5841d7eaa58dR15-R39): Added utility functions `hexToRgb` and `isColorDark` to process and determine color brightness.

These changes collectively enable users to customize the theme color and ensure the application handles color selection and theme application effectively.

2025-02-17 14:27 UTC, mvllow requested changes
Can you please format this via `npx prettier --write .` to make it easier to review?

2025-02-17 14:28 UTC, jatindotdev commented
> Can you please format this via `npx prettier --write .` to make it easier to review?

sure!

2025-02-17 15:03 UTC, mvllow requested changes

2025-02-17 15:03 UTC, mvllow commented on src/store/options.ts
> +		setCustomColor(colorHex: string) {
Currently, "#30" or other invalid hex values will show a white background with light text as well breaking other parts of the UI. A simple, yet naïve solution would be to ensure the hex length (minus the hash) is 3 or 6 characters. Ideally we would have validation on the input itself to ensure the value is actually a hex value, e.g. "#g00" would be invalid.

Correct me if I'm wrong but I don't think we need to support transparency so a regex could be:

```js
// https://stackoverflow.com/a/8027444
/^#([0-9A-F]{3}){1,2}$/i.test('#ABC')
```

2025-02-17 15:19 UTC, jatindotdev commented on src/utils/helpers.ts
> +	// HSP (Highly Sensitive Poo) equation from http://alienryderflex.com/hsp.html
https://awik.io/determine-color-bright-dark-using-javascript
as per above url, it mentioned that in the code for i kept it for reference

2025-02-17 15:24 UTC, jatindotdev commented on src/utils/helpers.ts
> +	hex = hex.slice(1)
https://github.com/fvrests/lavender/blob/e372c28a8233057757fe4f474c3d952deecd197c/src/components/options.vue#L30-L37
we handle that here, so every time we will get a hex with a #

2025-02-17 15:36 UTC, jatindotdev commented on src/store/options.ts
> +		setCustomColor(colorHex: string) {
let me make some fix over here! will get back to you in sometime for this

2025-02-17 17:56 UTC, jatindotdev commented on src/store/options.ts
> +		setCustomColor(colorHex: string) {
@mvllow i think we should be good, i made this change but kept it on the vue file instead!

2025-02-17 18:05 UTC, jatindotdev commented on src/store/options.ts
> +		setCustomColor(colorHex: string) {
https://github.com/fvrests/lavender/blob/47c454033d40f68a95f4dfb175b96d7384f8e3bc/src/components/options.vue#L34-L50

here the color only changes if its either empty or if #333 or #333333

2025-02-17 18:06 UTC, jatindotdev commented on src/store/options.ts
> +		setCustomColor(colorHex: string) {
i have also added a input length limit to be 7 characters at max

2025-02-19 19:39 UTC, mvllow approved these changes

2025-02-19 19:46 UTC, merged

2025-02-20 18:37 UTC, jatindotdev commented
Thank you! It was a fun challenge, and I’m glad you liked the solution. Excited to see it go live soon 😊